services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: mini-crm-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.4
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: mini_crm
      MYSQL_USER: mini_crm
      MYSQL_PASSWORD: mini_crm
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
